### ISSUE TITLE
[Question] Can we donate our actions to the reviewdog organization?

### ISSUE THREAD

**Issue by yu-iskw** [reviewdog/action-composite-template#9]
Hi @haya14busa, I have a question about the organization.
I built a github action to scan IaC files with terrascan using reviewdog. I would love to donate it to the organization.

https://github.com/yu-iskw/action-terrascan

## What is terrascan?
https://github.com/accurics/terrascan

> Terrascan is a static code analyzer for Infrastructure as Code. Terrascan allows you to:
>
> Seamlessly scan infrastructure as code for misconfigurations.
> Monitor provisioned cloud infrastructure for configuration changes that introduce posture drift, and enables reverting to a secure posture.
> Detect security vulnerabilities and compliance violations.
> Mitigate risks before provisioning cloud native infrastructure.
> Offers flexibility to run locally or integrate with your CI\CD.

**Comment by haya14busa** [comment]
Hi @yu-iskw 

The action looks great!
You can donate to the reviewdog org via https://opencollective.com/reviewdog, or please donate individual reviewdog contributors separately.
